Community project files and CI starting with formatting
caikit/caikit-huggingface-demo pull request #11
Opened 2023-06-02 00:05 UTC by markstur

By default, check black and isort on Python 3.8 (minimum supported version). Provide additional tasks for auto-fix and other python versions. Provide tasks for future lint (not passing yet) and tests.

2023-06-26 17:27 UTC, hickeyma requested changes

2023-06-26 17:27 UTC, hickeyma commented on SECURITY.md
> +The Caikit project has a [common security policy that can be found here](https://github.com/caikit/community/blob/main/SECURITY.md).
Caikit project --> Caikit community

2023-06-26 17:27 UTC, hickeyma commented on code-of-conduct.md
> +The Caikit project [has a common code of conduct that can be found here](https://github.com/caikit/community/blob/main/code-of-conduct.md).
Caikit project --> Caikit community

2023-06-26 17:27 UTC, hickeyma commented on CODEOWNERS
> +# List of approvers for caikit/caikit repository
caikit/caikit --> caikit/caikit-huggingface-demo

2023-06-26 17:27 UTC, hickeyma commented on CONTRIBUTING.md
> +Before sending pull requests, make sure your changes pass formatting, linting and unit tests.
Do unit tests exists?

2023-06-26 17:27 UTC, hickeyma commented on CONTRIBUTING.md
> +- Run tests locally and ensure they pass
Do tests exists?

2023-06-26 17:27 UTC, hickeyma commented on CONTRIBUTING.md
> +The responsibility for releasing new versions of the libraries falls to the maintainers. Releases will follow standard [semantic versioning](https://semver.org/).
Not applicable

2023-07-13 20:24 UTC, markstur commented
addressed review comments

2023-07-17 17:03 UTC, hickeyma approved these changes

2023-07-17 17:04 UTC, merged